# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Description: macOS Network Usage Monitor
class Netmon < Formula
  desc "macOS Network Usage Monitor - Track network usage by interface and application"
  homepage "https://github.com/abcdOfficialzw/netmon"
  url "https://github.com/abcdOfficialzw/netmon.git", branch: "main"
  version "HEAD"
  license "MIT"

  depends_on "go" => :build

  def install
    # Set up Go environment
    ENV["GO111MODULE"] = "on"

    # Build netmon-service
    system "go", "build", "-o", "netmon-service", "./cmd/netmon-service"

    # Build netmon CLI
    system "go", "build", "-o", "netmon", "./cmd/netmon"

    # Install binaries
    bin.install "netmon-service"
    bin.install "netmon"
  end

  test do
    # Test that binaries exist and are executable
    assert_match "Usage:", shell_output("#{bin}/netmon 2>&1", 1)
    assert_match "Usage of", shell_output("#{bin}/netmon-service --help 2>&1")
  end

  def post_install
    # Print helpful message after installation
    ohai "netmon installed successfully!"
    ohai ""
    ohai "Next steps:"
    ohai "  1. Run: netmon setup"
    ohai "  2. This will configure the background service"
    ohai "  3. Then use: netmon (to view stats)"
    ohai ""
    ohai "For more info, visit: #{homepage}"
  end
end

